ABI-Software/scaffoldvuer

package-lock.json, src/App.vue, src/components/ScaffoldVuer.vue
=> Add help mode to app and switch popups to purple

package.json, src/components/ScaffoldVuer.vue, src/components/TraditionalControls.vue
Fix a bug causing undefined item on checkbox group.
Add loading screen.
=> Release 0.1.34

package-lock.json, package.json, src/components/ScaffoldVuer.vue, src/components/TraditionalControls.vue
Add Beta text.
Display all only shows up when there is more than one item on list.
Fixa a problem with loading page for scaffolds without labels.
=> version 0.1.38.

src/App.vue, src/components/ScaffoldVuer.vue
This will be used to link the time of the model with other components
=> Add an emit output for time of the scene

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue
Now with an option to show marker and use it for picking.
New timeChanged event has been added.
=> Version0.1.39

package-lock.json, package.json, src/App.vue, src/components/OpacityControls.vue, src/components/ScaffoldVuer.vue, src/components/TraditionalControls.vue
Improve on the demo interface.
=> Add minimap

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue, vue.config.js
State APIs for setting and getting current state of the application.
=> State APIs

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue, src/components/TraditionalControls.vue
Update icons and overhaul UIs.
=> UI improvements

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue
Improve time slider displays and functionality.
=> Animation displays

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue, src/components/TraditionalControls.vue
Add support for specifying viewport file and region.
=> Support new viewURL and region props.

package-lock.json, package.json, src/components/ScaffoldVuer.vue
Fix a bug causing zoom in to not work as intended.
=> Zoom in fix

package-lock.json, package.json, src/components/OpacityControls.vue, src/components/ScaffoldVuer.vue, src/components/TraditionalControls.vue
Improve opacity box and make it collapsible.
=> Opacity box

package-lock.json, package.json, src/components/ScaffoldVuer.vue, src/scripts/BaseModule.js, src/scripts/RendererModule.js, src/scripts/WebGL.js, src/scripts/annotation.js, src/scripts/eventNotifier.js, src/scripts/graphicsHighlight.js, src/scripts/organsRenderer.js, vue.config.js
Use zinc version 0.41.2 which fixes some of the rendering problem. Time dependent colour on lines are now supported.
=> Update dependencies and bug fixes

package-lock.json, src/App.vue, src/components/ScaffoldTooltip.vue, src/components/ScaffoldVuer.vue, src/components/TreeControls.vue, src/scripts/organsRenderer.js, src/scripts/utilities.js
Improve performance by removing zinc objects that should not be reactive.
=> Improve performance

README.md
More detailed release documentation coming soon
=> Add publish and versioning instructions to readme

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue, src/scripts/search.js, src/scripts/utilities.js
Can test the search in App.vue and also in mapintegratedvuer
https://github.com/ABI-Software/mapintegratedvuer/pull/157
=> Create working search in scaffoldvuer

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue, src/components/TreeControls.vue, src/scripts/RendererModule.js, src/scripts/organsRenderer.js, src/scripts/utilities.js
Add supports to enable marker for a specific zinc object.
Marker will always be prioritised with the picker.
=> Supports concurrent markers and primitives picking. Markers picking is always prioritised.

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue
Added a prop which takes in a list of algolia facet labels.
This list then updates the markers on the scaffold.
Note that I had to wait for scaffold ready on the first facet label change
=> Add prop for setting markers

package-lock.json, package.json, src/App.vue, src/components/ScaffoldTooltip.vue, src/components/ScaffoldVuer.vue
Add annotation UI, which is a part of flatmapvuer.
=> Annotation UI

package-lock.json, package.json, vuese-generator.js
1. Removed unused npm packages.
2. Replaced @vuese/cli with @vuese/markdown-render and @vuese/parser because @vuese/cli has dependencies with vulnerabilities.
No functionalities or UI updates are included.
Tested visual checks and bundled in another package.
=> NPM Issues Fix

docs/.vitepress/config.js, docs/index.md
This is just a content update for the doc title and button style change.
=> Update docs content

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue
=> Support markers with image data.

src/components/ScaffoldVuer.vue
=> Update switch viewing mode UI

package-lock.json, package.json, src/App.vue, src/components/ScaffoldVuer.vue
Allow to change the viewing mode in mapvuer.
=> Map annotation shortcut

src/components/ScaffoldTooltip.vue, src/components/ScaffoldVuer.vue, src/scripts/Utilities.js
This update will make the behaviour on annotation mode to be more consistent with flatmapvuer's one.
=> Annotation

src/App.vue, src/scripts/Search.js
The auto suggestion from the minisearch library is confusing and returns tokenised terms where a full string would work much better. I replaced it with my own implementation. Term in double quote is now supported for exact match similar to flatmapvuer as well.
=> Improve searching, making it consistent with flatmapvuer.

package-lock.json, package.json, src/components.d.ts, src/components/ScaffoldVuer.vue
Require the following PR:
- https://github.com/ABI-Software/map-utilities/pull/19
One line change to make sure the toolbar behaviour be the same as flatmapvuer
=> Annotation toolbar update
